name: Build docs

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6
      - name: setup jdk
        uses: actions/setup-python@v6
        with:
          python-version: "3.14.x"
      - name: setup venv
        run: python3 -m venv .venv
      - name: install deps
        run: .venv/bin/pip3 install -r requirements.txt
      - name: Build
        run: .venv/bin/mkdocs build
