name: Build docs

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: git.raphdf201.net/raphdf201/images:python-node
    steps:
      - name: Checkout
        uses: actions/checkout@v6
      - name: setup venv
        run: python3 -m venv .venv
      - name: install deps
        run: .venv/bin/pip3 install -r requirements.txt
      - name: Build
        run: .venv/bin/mkdocs build
